### ISSUE TITLE
redesign the frontend page of the code 

### ISSUE THREAD

**Issue by azru007** [azru007/KTUSTUDYGUIDE#1]
the page need to contain the all the departements both in navbar and in the card section the ui should look good

**Comment by azru007** [comment]
it should also connect to the years page  it should  contain like 6 departements minimum of ktu  departement like cse,ece,eee.mech,it,civil and the navbar should contain  mainly the departements with dropdown menu of semster this way they can directly go to semster if they use navbar

**Comment by shadil-rayyan** [comment]
can i work on this i will fix the ui and connect it to each other i am ktu student as well

**Comment by azru007** [comment]
go ahead, read the contributing file before doing the pull requests

**Comment by azru007** [comment]
as we talked i made the changes as we need

**Comment by azru007** [comment]
i looked the code you send its ok i accepeted your pull request as well

**Comment by azru007** [comment]
ok the issue is over for now we will change the ui in the future
